"""initial migration

Revision ID: 2bd6ae271f09
Revises: 
Create Date: 2026-05-19 15:42:20.146804

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bd6ae271f09"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    # op.drop_index(op.f("ix_order_items_id"), table_name="order_items")
    op.drop_table("order_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("product_name", sa.VARCHAR(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("price", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("order_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_items_id"), "order_items", ["id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("customer_name", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    # ### end Alembic commands ###
